name: polegeo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - blinker=1.6.2=py39h06a4308_0
  - branca=0.7.1=pyhd8ed1ab_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py39h5a03fae_7
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=py39h06a4308_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - eigen=3.4.0=hdb19cb5_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - flask=3.0.2=pyhd8ed1ab_0
  - folium=0.16.0=pyhd8ed1ab_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopy=2.4.1=pyhd8ed1ab_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - harfbuzz=4.3.0=hf52aaf7_1
  - hdf5=1.12.1=h2b7332f_3
  - icu=58.2=he6710b0_3
  - idna=3.6=pyhd8ed1ab_0
  - importlib_resources=6.1.1=py39h06a4308_1
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jinja2=3.1.3=py39h06a4308_0
  - joblib=1.2.0=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.5.0=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - lz4-c=1.9.4=h6a678d5_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.7=py39h286c3b5_0
  - numpy-base=1.26.3=py39h8a23956_0
  - opencv=4.6.0=py39ha16400d_5
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - pcre=8.45=h295c915_0
  - pillow=10.2.0=py39h5eee18b_0
  - pixman=0.40.0=h7f8727e_1
  - pyparsing=3.0.9=py39h06a4308_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2023.3.post1=py39h06a4308_0
  - qt-main=5.15.2=h7358343_9
  - qt-webengine=5.15.9=h9ab4d14_7
  - qtwebkit=5.212=h3fafdc1_5
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - seaborn=0.12.2=py39h06a4308_0
  - setuptools=68.2.2=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023d=h04d1e81_0
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.41.2=py39h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.4.5=h5eee18b_0
  - zipp=3.17.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - affine==2.4.0
    - annotated-types==0.6.0
    - anyio==4.2.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - bottleneck==1.3.6
    - cffi==1.16.0
    - click-plugins==1.1.1
    - cligj==0.7.2
    - colorama==0.4.6
    - comm==0.2.1
    - contextily==1.6.0
    - cv-bridge==1.13.0.post0
    - debugpy==1.8.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dtw==1.4.0
    - dtw-python==1.5.1
    - et-xmlfile==1.1.0
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fastjsonschema==2.19.1
    - filelock==3.9.0
    - fqdn==1.5.1
    - fsspec==2023.4.0
    - gitdb==4.0.11
    - gitpython==3.1.41
    - h11==0.14.0
    - httpcore==1.0.2
    - httpx==0.26.0
    - ifaddr==0.2.0
    - importlib-metadata==6.6.0
    - ipykernel==6.29.2
    - ipython==8.18.1
    - isoduration==20.11.0
    - jedi==0.19.1
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.0
    - jupyter-core==5.7.1
    - jupyter-events==0.9.0
    - jupyter-http-over-ws==0.0.8
    - jupyter-lsp==2.2.2
    - jupyter-server==2.12.5
    - jupyter-server-terminals==0.5.2
    - jupyterlab==4.1.0
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.2
    - kiss-icp==0.3.0
    - laspy==2.5.3
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.8.3
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mercantile==1.2.1
    - mistune==3.0.2
    - more-itertools==10.2.0
    - mpmath==1.3.0
    - natsort==8.4.0
    - nbclient==0.9.0
    - nbconvert==7.16.0
    - nbformat==5.9.2
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - notebook==7.0.7
    - notebook-shim==0.2.3
    - numpy==1.26.4
    - open3d==0.18.0
    - opencv-python==4.9.0.80
    - openpyxl==3.1.2
    - ouster-mapping==0.1.1
    - ouster-sdk==0.10.0
    - overrides==7.7.0
    - packaging==23.2
    - pandas==2.2.2
    - pandocfilters==1.5.1
    - parso==0.8.3
    - pexpect==4.9.0
    - pip==24.3.1
    - platformdirs==4.2.0
    - plyfile==1.0.3
    - prettytable==3.10.0
    - prometheus-client==0.19.0
    - prompt-toolkit==3.0.43
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-cpuinfo==9.0.0
    - pyarrow==16.1.0
    - pycparser==2.21
    - pydantic==2.6.3
    - pydantic-core==2.16.3
    - pydantic-settings==2.2.1
    - pygments==2.17.2
    - pykrige==1.7.2
    - python-dotenv==1.0.1
    - python-json-logger==2.0.7
    - python-magic==0.4.27
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - rasterio==1.3.10
    - referencing==0.33.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.7.0
    - rpds-py==0.17.1
    - scikit-learn==1.4.0
    - scipy==1.13.1
    - send2trash==1.8.2
    - shellingham==1.5.4
    - smmap==5.0.1
    - sniffio==1.3.0
    - snuggs==1.4.7
    - soupsieve==2.5
    - stack-data==0.6.3
    - sympy==1.12
    - terminado==0.18.0
    - thop==0.1.1-2209072238
    - tinycss2==1.2.1
    - torch==2.2.0+cpu
    - torchaudio==2.2.0+cpu
    - torchvision==0.17.0+cpu
    - tornado==6.4
    - traitlets==5.14.1
    - typer==0.9.0
    - types-python-dateutil==2.8.19.20240106
    - typing-extensions==4.9.0
    - ultralytics==8.1.11
    - uri-template==1.3.0
    - urllib3==2.2.0
    - utm==0.7.0
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - zeroconf==0.58.2
prefix: /home/durgab/anaconda3/envs/polegeo
